### ISSUE TITLE
[PE-D][Tester C] Phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-1/tp#151] opened 2022-10-29 04:44 UTC
The phone number allows parsing of very long numbers that should not be possible. Maybe want to set a limit on this?

![Screenshot (89).png](https://raw.githubusercontent.com/maxng17/ped/main/files/94e65d4c-b759-47cc-9e13-83d6607788af.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: maxng17/ped#12

**Comment by comicalromance** [comment] 2022-11-02 08:56
Closed as duplicate of #126

**Closed by comicalromance** 2022-11-02 08:56 UTC
Labels: bug
