### ISSUE TITLE
[PE-D][Tester A] Formatting errors with command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-1/tp#128] opened 2022-10-29 02:45 UTC
![image.png](https://raw.githubusercontent.com/charleslimjh/ped/main/files/11af55e0-3fd5-4799-8436-748d4fcae782.png)

Table headers for the command summary are not formatted properly.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: charleslimjh/ped#2

**Comment by comicalromance** [comment] 2022-11-02 09:12
duplicate of #153

**Closed by comicalromance** 2022-11-02 09:12 UTC
Labels: bug, duplicate
